version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "gigamogdeployment"
    BUILD_FOLDER: "build/libs"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing dependencies...
      - gradle wrapper
      - ./gradlew install
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew fatJar
  post_build:
    commands:
      - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build/libs*'
  discard-paths: yes
