version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradle test
  post_build:
    commands:
      - gradle bootJar
      - echo Build completed on `date`
artifacts:
  files:
    - build/*
    - appspec.yml
  discard-paths: yes