version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - ./gradlew clean install
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew bootJar
  post_build:
    commands:
      - ./gradlew docker
      - ./gradlew dockerPush
artifacts:
  files:
    - '**/*'
  base-directory: 'build*'
  discard-paths: yes
