version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - ./gradlew clean install
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew bootJar
  post_build:
    commands:
      - docker build -t sephto/pointing:latest .
      - docker push sephto/pointing:latest
artifacts:
  files:
    - '**/*'
  base-directory: 'build*'
  discard-paths: yes
