version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - ./gradlew build
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew bootJar
  post_build:
    commands:
      - ./gradlew docker
      - sh -c "docker login -u $USERNAME -p $PASSWORD"
      - ./gradlew dockerPush
      - aws s3 cp s3://gigamogdeployment/secrets/pointingpoker.pem pointingpoker.pem
      - chmod 400 pointingpoker.pem
      - ssh -i "pointingpoker.pem" ec2-user@ec2-18-220-162-194.us-east-2.compute.amazonaws.com -y
      - cd pointing-docker-compose
      - docker-compose up --force-recreate --build
      - docker image prune -f
artifacts:
  files:
    - '**/*'
  base-directory: 'build*'
  discard-paths: yes
